version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: sushantjoshi12/your-image-repo-name
    IMAGE_TAG: latest
    DOCKERHUB_USERNAME: sushantjoshi12
    DOCKERHUB_PASSWORD: Mahi@7781

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Update apt-get and install Docker
      - echo Installing Docker on Ubuntu...
      - apt-get update
      - apt-get install -y docker.io
      - docker --version  # Verify that Docker is installed# Install Python dependencies if needed
      - echo "Checking for requirements.txt..."
       - ls -l requirements.txt
       - apt-get update
       - echo Installing Python dependencies...
      - pip install  -r requirements.txt

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Tagging the image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  build:
    commands:
      - echo Build completed

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - build_output/**/*   # Include all files from the build_output folder
    - logs/**/*.log        # Include all .log files from logs folder
  discard-paths: yes 
